name: CI

on:
  [push, pull_request, workflow_dispatch]

jobs:
  linting-checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up uv
      uses: astral-sh/setup-uv@v4
      with:
        python-version: "3.14"
    - name: Install dependencies
      run: uv sync --frozen --group dev
    - name: Run checks
      run: |
        uv run isort --verbose --check-only --diff src tests
        uv run flake8 src tests
        # uv run pylint src tests

  docs-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install pandoc
      run: sudo apt-get install pandoc
    - name: Set up uv
      uses: astral-sh/setup-uv@v4
      with:
        python-version: "3.14"
    - name: Install dependencies
      run: uv sync --frozen --group docs
    - name: Test build docs
      run: |
        uv run sphinx-build -E -j auto -b doctest docs dist/docs
        uv run sphinx-build -E -j auto -b html docs dist/docs
        uv run sphinx-build -j auto -b linkcheck docs dist/docs

  unit-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13', '3.14']

    steps:
    - uses: actions/checkout@v4
    - name: Set up uv
      uses: astral-sh/setup-uv@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install package
      run: uv sync --frozen --group test
    - name: Run tests
      run: uv run pytest --cov --cov-report=term-missing -vv
    - name: Report coverage
      run: uv run codecov


  build-publish:
    runs-on: ubuntu-latest
    needs: [linting-checks, docs-build, unit-tests]
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up uv
      uses: astral-sh/setup-uv@v4
    - name: Build wheels
      run: uv build
    - name: Publish 📦 to Test PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
        verbose: true
    - name: Publish 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
    - name: GH 🐱🐙 Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
